#!/usr/bin/env python

import os
import errno
import shutil
import time
import datetime


InFile = input("File names from eSlideManager:")
myDestination = input("Your Drive and folder name to save data: ")
# need an input for Disk and location info for source files

#pathToDatefolderOnSource = input("mySource/images/" ), including disk volume. 

srcFiles = []
DestList = [] 

ts = time.time()
TimeNow = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
print("Time now is: ", TimeNow)
timeStart = time.time()



fileHandle = open(InFile, "r")
lineNum = 0
for Line in fileHandle: 
    Line = Line.strip('\n')
    if lineNum > 0: 
       immediateFolder = Line.split("\\")[-2]
       fileName = Line.split("\\")[-1].strip('",')
       srcFiles.append("mySource/images/" + immediateFolder +"/"+fileName)
       DestList.append(myDestination + "/" + immediateFolder+"/")
    lineNum += 1
fileHandle.close()
print("You have " + str(len(srcFiles)) + " files to copy")

# create destination dirs and make that into a list
for i in DestList: 
    newDir =  i
    if not os.path.exists(newDir):
         os.makedirs(newDir)


    
##### copying 
fileCopied = 0
for i in range(0, len(srcFiles)):
    shutil.copy(srcFiles[i], DestList[i])
    fileCopied += 1
########
print(str(fileCopied) + " files copied")

########
## showing user clock time elapsed
timeEnd = time.time()
timeUsed = timeEnd - timeStart
print("Time used: " + "%20.4F" %timeUsed + " seconds")
