#!/usr/bin/env python

import os, errno, shutil, time, datetime

InFile = input("The csv file name exported from eSlideManager: ")
myDestination = input("Your Drive and folder name to save data: ")

#the following variable may change depending on the attachment of our external AperioBackup disk
#which is sitting on top of the Aperio CS ScanScope computer 
folderOnSeagateA214 = "H:/AperioBackup/" 

ts = time.time()
TimeNow = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')
print("Time now is: ", TimeNow)
timeStart = time.time()

srcFiles = []
DestList = [] 
try:
    fileHandle = open(InFile, "r")
except:
    print("File can't be opened: ", InFile)
    quit()
    
lineNum = 0
for Line in fileHandle: 
    Line = Line.strip('\n')
    if lineNum > 0: 
       immediateFolder = Line.split("\\")[-2]
       fileName = Line.split("\\")[-1].strip('",')
       srcFiles.append(folderOnSeagateA214 + immediateFolder +"/"+fileName)
       DestList.append(myDestination + "/" + immediateFolder+"/")
    lineNum += 1
fileHandle.close()

##### create destination dirs and make into a list
for i in DestList: 
    newDir =  i
    if not os.path.exists(newDir):
         os.makedirs(newDir)
    
##### copying 
fileCopied = 0
print("Copying...")
for i in range(0, len(srcFiles)):
    shutil.copy(srcFiles[i], DestList[i])
    fileCopied += 1
    if fileCopied % 5 == 0:
      print("Backup is ongoing, " + str(fileCopied) + " files copied so far")
print("You have " + str(len(srcFiles)) + " files to copy")
print("In total, " + str(fileCopied) + " files copied for you")

##### showing user clock time elapsed
timeEnd = time.time()
timeUsed = timeEnd - timeStart
print("Time used: " + "%10.4F" %timeUsed + " seconds")

#### the end
